apiVersion: v1
kind: Service
metadata:
  name: neo4j-service
spec:
  selector:
    app: neo4j
  ports:
  - protocol: TCP
    port: 7474
    targetPort: 7474
    name: neo4j-http
  - protocol: TCP
    port: 7687
    targetPort: 7687
    name: neo4j-bolt
