apiVersion: v1
kind: Service
metadata:
  labels:
    app: clingen-kb
  name: clingen-kb
spec:
  type: LoadBalancer
  loadBalancerIP: 35.231.216.197
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: clingen-kb
    - port: 443
      targetPort: 443
      protocol: TCP
      name: clingen-kb-ssl
  selector:
    app: clingen-kb
  
