# https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/ssd-pd
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Release.Name }}-gce-pd-ssd-sc
  labels:
    {{- include "clingen-vicc.labels" . | nindent 4 }}
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
