apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-variation-normalizer
  labels:
    app: variation-normalizer
    {{- include "clingen-vicc.labels" . | nindent 4 }}
spec:
  serviceName: {{ .Release.Name }}-variation-normalizer-svc
  replicas: 1
  selector:
    matchLabels:
      app: variation-normalizer
      {{- include "clingen-vicc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: variation-normalizer
        {{- include "clingen-vicc.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: aws-credentials
          configMap:
            name: {{ .Release.Name }}-aws-creds-configmap
            items:
              - key: credentials
                path: credentials
      initContainers:
        - image: gcr.io/clingen-dev/vicc-seqrepo-populator:2021-01-29
          imagePullPolicy: Always
          name: seqrepo-populator
          env:
            # Directory the seqrepo release will be written into, DATA_DIR/seqrepo/<seqrepo-version>
            - name: DATA_DIR
              value: "/usr/local/share"
          resources:
            requests:
              cpu: 0.5
            limits:
              memory: 512Mi
          volumeMounts:
            - name: {{ .Release.Name }}-varnorm-seqrepo-pvc
              mountPath: "/usr/local/share/seqrepo"

      containers:
        - name: varnorm
          image: gcr.io/clingen-dev/cancervariants/variation-normalization:5e87d846231b1e8d1e06b3cd811de6e170b5bb73
          imagePullPolicy: Always
          env:
            - name: SEQREPO_DATA_PATH
              value: "/usr/local/share/seqrepo/2021-01-29"
            - name: GENE_NORM_DB_URL
              value: "http://{{- .Release.Name -}}-gene-normalizer-svc:8000"
            - name: UTA_DB_URL
              value: "postgresql://uta_admin:{{- .Values.uta_admin_password -}}@{{- .Release.Name -}}-uta-svc:5432/uta/uta_20210129"
          ports:
            - containerPort: 80
              name: varnorm-port
          volumeMounts:
            - name: {{ .Release.Name }}-varnorm-seqrepo-pvc
              mountPath: "/usr/local/share/seqrepo"
            - name: aws-credentials
              mountPath: "/root/.aws/credentials"
              subPath: "credentials"
              readOnly: true
          # command:
          #   - bash
          #   - -c
          #   - 'while true; do sleep 10; done'

  volumeClaimTemplates:
    - metadata:
        name: {{ .Release.Name }}-varnorm-seqrepo-pvc
        labels:
          {{- include "clingen-vicc.labels" . | nindent 10 }}
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Release.Name }}-gce-pd-ssd-sc
        resources:
          requests:
            storage: 25Gi

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-variation-normalizer-svc
  labels:
    {{- include "clingen-vicc.labels" . | nindent 4 }}
spec:
  selector:
    app: variation-normalizer
    {{- include "clingen-vicc.selectorLabels" . | nindent 4 }}
  type: ClusterIP # stable cluster IP
  ports:
    - name: varnorm-port
      port: 80
      targetPort: varnorm-port
      protocol: TCP
