# in order of appearance in the helm templates
# deployment
genegraph_docker_image_name: gcr.io/clingen-stage/genegraph
genegraph_docker_image_tag: clinvar.49677cf3763cbbc9419d11a18360576fde7c55da
genegraph_data_version: "2022-03-31T1453"
genegraph_image_version_envvar: true
genegraph_cg_search_topics: "clinvar-raw"
genegraph_gcs_bucket: genegraph-stage
genegraph_gql_cache: false
genegraph_validate_events: false
genegraph_response_cache: false
genegraph_experimental_schema: true
genegraph_dx_jaas_secretname: confluent-stage-jaas
# certificate and ingress
genegraph_mcrt_domains:
  - 'genegraph-clinvar.stage.clingen.app'
genegraph_static_ip_name: clingen-genegraph-stage-clinvar-ip
# storage
genegraph_local_ssd: true
# run migration job before deployment
genegraph_run_migration: true
genegraph_migration_data_version: "2022-03-16T1345:f04c571c5bec539e5c9e467e64539a644d651d49"
