# in order of appearance in the helm templates
# deployment
genegraph_updateStrategy: false
genegraph_configure_pod_antiaffinity: false
genegraph_docker_image_name: gcr.io/clingen-dev/genegraph
genegraph_docker_image_tag: cv-latest
genegraph_data_version: "2020-12-17T1429"
genegraph_include_serveur_keypass: true
genegraph_cg_search_topics: "clinvar-combined"
genegraph_gcs_bucket: genegraph-dev
genegraph_gql_cache: false
genegraph_validate_events: true
genegraph_response_cache: false
genegraph_dx_jaas_secretname: dx-dev-jaas
genegraph_readiness_probe_path: /live
genegraph_configureLivenessProbe: false

# certificate and ingress
genegraph_tls_cert: true
genegraph_mcrt_name: clingen-app-certificate
genegraph_mcrt_domains:
- 'genegraph-dev.clingen.app'
genegraph_configure_ingress: true
genegraph_static_ip_name: genegraph-clinvar-ip

# service
genegraph_service: true
genegraph_service_type: NodePort
genegraph_port: 8888

# storageclass
genegraph_configure_storageclass: false
