# in order of appearance in the helm templates
# deployment
genegraph_docker_image_name: gcr.io/clingen-dev/genegraph
genegraph_docker_image_tag: dev-deploy
genegraph_data_version: "2022-02-07T1753:25fb2b9d270ad4a7f7392b1cce0004dad4e0b21d"
genegraph_image_version_envvar: true
genegraph_cg_search_topics: "clinvar-raw"
genegraph_gcs_bucket: genegraph-dev
genegraph_gql_cache: false
genegraph_validate_events: false
genegraph_response_cache: false
genegraph_experimental_schema: true
genegraph_dx_jaas_secretname: dx-dev-jaas
# certificate and ingress
genegraph_mcrt_domains:
  - 'genegraph-dev-clinvar.clingen.app'
genegraph_static_ip_name: global-dev-genegraph-clinvar-ip


genegraph_deployment_resources:
  requests:
    memory: 1Gi
    cpu: 0.25
  limits:
    memory: 1Gi


# storage
genegraph_local_ssd: false
genegraph_configure_storageclass: true
genegraph_persistent_disk:
  size: 750Gi

# Override readiness probe to mark ready immediately
genegraph_readiness_probe:
  periodSeconds: 30
  successThreshold: 1
  httpGet:
    path: /live
    port: genegraph-port

# run migration job before deployment
genegraph_run_migration: false
#genegraph_migration_data_version: "2022-02-07T1753:25fb2b9d270ad4a7f7392b1cce0004dad4e0b21d"

# include nrepl
genegraph_nrepl_port: 6000

# rocksdb http
genegraph_rocksdb_registry_uri: http://vrs-cache-registry-svc:6381
vrs_normalization_service: "http://variation-normalizer-variation-normalizer-svc:80/variation"


genegraph_command: ["java", "-Xmx400m", "-jar", "/app/app.jar"]
