# in order of appearance in the helm templates
# deployment
genegraph_docker_image_name: gcr.io/clingen-dev/genegraph
genegraph_docker_image_tag: clinvar.5f43d8b71c59a4c042de6f9849cd9e833f2d52c0
genegraph_data_version: "2022-03-25T1836"
genegraph_image_version_envvar: true
genegraph_cg_search_topics: "clinvar-raw"
genegraph_gcs_bucket: genegraph-dev
genegraph_gql_cache: false
genegraph_validate_events: false
genegraph_response_cache: false
genegraph_experimental_schema: true
genegraph_dx_jaas_secretname: dx-dev-jaas
# certificate and ingress
genegraph_mcrt_domains:
  - 'genegraph-dev-clinvar.clingen.app'
genegraph_static_ip_name: global-dev-genegraph-clinvar-ip
# run migration job before deployment
genegraph_run_migration: false
