apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include  "clinvar-raw.chartLabels" . | nindent 4 }}
spec:
  serviceName: {{ .Release.Name }}-svc
  selector:
    matchLabels:
      {{- include "clinvar-raw.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "clinvar-raw.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 600
      volumes:
        - name: {{ .Release.Name }}-vol
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc
      containers:
        - image: "{{ .Values.clinvar_streams_docker_image_name }}:{{ .Values.clinvar_streams_docker_image_tag }}"
          imagePullPolicy: {{ .Values.clinvar_streams_image_pull_policy }}
          name: clinvar-raw
          {{- with .Values.clinvar_streams_deployment_resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: {{ .Release.Name }}-vol
              mountPath: "/data/"
          env:
            - name: CLINVAR_STREAMS_DATA_DIR
              value: "/data/"
            - name: DX_CV_RAW_INPUT_TOPIC
              value: {{ .Values.clinvar_raw_input_topic }}
            - name: DX_CV_RAW_OUTPUT_TOPIC
              value: {{ .Values.clinvar_raw_output_topic }}
            - name: KAFKA_USER
              valueFrom:
                secretKeyRef:
                  name: "dx-creds-{{ .Release.Name }}"
                  key: user
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "dx-creds-{{ .Release.Name }}"
                  key: password
            - name: KAFKA_GROUP
              value: "{{ .Values.clinvar_streams_kafka_group }}"
          args:
            - clinvar-raw
          ports:
            - containerPort: 8080
              name: service-port
          lifecycle:
            preStop:
              httpGet:
                # host defaults to pod IP
                path: "PreStop"
                port: 8080
