apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
  labels:
    {{- include  "clinvar-raw.chartLabels" . | nindent 4 }}
spec:
  storageClassName: {{ .Release.Name }}-storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 75Gi
