apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dx-creds-{{ .Release.Name }}
  labels:
    {{- include  "clinvar-raw.chartLabels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsecretsmanager-secretstore
  target:
    name: dx-creds-{{ .Release.Name }} # K8S ExternalSecret resource name
  dataFrom:
  - extract:
      key: kafka-credentials # Google Secret Manager secret name
