---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: argocd-server-http-ingress
  namespace: argocd
  annotations:
    # kubernetes.io/ingress.global-static-ip-name: global-dev-argocd-ip
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.static_ip_name }}
    networking.gke.io/managed-certificates: {{ .Values.managed_cert_name }}
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: argocd-server
          servicePort: http
    # host: argocd-dev.clingen.app
    host: {{ .Values.argo_host_name }}
  tls:
  - hosts:
    - {{ .Values.argo_host_name }}
    secretName: argocd-secret # do not change, this is provided by Argo CD
