env:
  POLLER_INTERVAL_MILLISECONDS: 120000
  WATCH_TIMEOUT: 360000
  GOOGLE_APPLICATION_CREDENTIALS: /app/gcp-creds/gcp-creds.json

filesFromSecret:
  gcp-creds:
    secret: gcp-creds
    mountPath: /app/gcp-creds
