apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "clingen-clinvar-submitter.fullname" . }}-ingress
  labels:
    {{- include "clingen-clinvar-submitter.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.ingress.static_ip_name }}
    networking.gke.io/managed-certificates: {{ include "clingen-clinvar-submitter.fullname" . }}-certificate
    kubernetes.io/ingress.class: "gce"
spec:
  backend:
    serviceName: {{ include "clingen-clinvar-submitter.fullname" . }}
    servicePort: {{ .Values.service.port }}
