---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: clinvar-scv-kafka-password
spec:
  backendType: gcpSecretsManager
  projectId: clingen-stage
  data:
    - key: clinvar-scv-kafka-password
      name: password
      version: latest
