apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: clinvar-scv-kafka-password
spec:
  data:
  - remoteRef:
      key: clinvar-scv-kafka-password
      version: latest
    secretKey: password
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsecretsmanager-secretstore
  target:
    name: clinvar-scv-kafka-password
