---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: clinvar-scv-kafka-user
spec:
  backendType: gcpSecretsManager
  projectId: clingen-stage
  data:
    - key: clinvar-scv-kafka-user
      name: user
      version: latest
