apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: confluent-stage-jaas
spec:
  data:
  - remoteRef:
      key: confluent-stage-jaas
      version: latest
    secretKey: password
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsecretsmanager-secretstore
  target:
    name: confluent-stage-jaas
