---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: neo4j-credentials
spec:
  backendType: gcpSecretsManager
  projectId: clingen-stage
  data:
    - key: neo4j-credentials
      name: password
      property: password
      version: latest
    - key: neo4j-credentials
      name: user
      property: user
      version: latest
