apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: neo4j-credentials
spec:
  data:
  - remoteRef:
      key: neo4j-credentials
      property: password
      version: latest
    secretKey: password
  - remoteRef:
      key: neo4j-credentials
      property: user
      version: latest
    secretKey: user
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsecretsmanager-secretstore
  target:
    name: neo4j-credentials
