apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: neo4j-url
spec:
  data:
  - remoteRef:
      key: neo4j-url
      version: latest
    secretKey: url
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsecretsmanager-secretstore
  target:
    name: neo4j-url
