---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  backendType: gcpSecretsManager
  projectId: clingen-dx
  data:
    - key: argocd-slack-token
      name: slack-token
      version: 1
