apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  data:
  - remoteRef:
      key: argocd-slack-token
      version: "1"
    secretKey: slack-token
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsecretsmanager-secretstore
  target:
    name: argocd-notifications-secret
