---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: clinvar-raw-credentials
spec:
  backendType: gcpSecretsManager
  projectId: clingen-dx
  data:
    - key: clinvar-raw-credentials
      name: password
      property: password
      version: latest
    - key: clinvar-raw-credentials
      name: user
      property: user
      version: latest
