apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: clingen-ssl
spec:
  data:
  - remoteRef:
      key: clingen-ssl
      property: clingen.crt
      version: "1"
    secretKey: clingen.crt
  - remoteRef:
      key: clingen-ssl
      property: clingen.key
      version: "1"
    secretKey: clingen.key
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsecretsmanager-secretstore
  target:
    name: clingen-ssl
