---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: clingen-ssl
spec:
  backendType: gcpSecretsManager
  projectId: clingen-dx
  data:
    - key: clingen-ssl
      name: clingen.crt
      property: clingen.crt
      version: 1
    - key: clingen-ssl
      name: clingen.key
      property: clingen.key
      version: 1
