---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: dx-stage-jaas
spec:
  backendType: gcpSecretsManager
  projectId: clingen-dx
  data:
    - key: dx-stage-jaas
      name: password
      version: latest
