apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kafka-credentials
spec:
  data:
  - remoteRef:
      key: kafka-credentials
      property: password
      version: "1"
    secretKey: password
  - remoteRef:
      key: kafka-credentials
      property: user
      version: "1"
    secretKey: user
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsecretsmanager-secretstore
  target:
    name: kafka-credentials
