---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: neo4j-url
spec:
  backendType: gcpSecretsManager
  projectId: clingen-dx
  data:
    - key: neo4j-url
      name: url
      version: latest
