apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: neo4j-url
spec:
  data:
  - remoteRef:
      key: neo4j-url
      version: "1"
    secretKey: url
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsecretsmanager-secretstore
  target:
    name: neo4j-url
