apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: gcpsecretsmanager-secretstore
spec:
  provider:
    gcpsm:
      auth:
        secretAccessKeySecretRef:
          name: gcpsm-secret
          key: secret-access-credentials
          namespace: external-secrets
      projectID: clingen-dx
