apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: gcpsecretsmanager-secretstore
spec:
  provider:
    gcpsm:
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-creds
            key: gcp-creds.json
            namespace: external-secrets
      projectID: clingen-dx
