---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: serveur-key-pass
spec:
  backendType: gcpSecretsManager
  projectId: clingen-dx
  data:
    - key: serveur-key-pass
      name: password
      version: latest
