apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: serveur-key
spec:
  data:
  - remoteRef:
      key: serveur-key
      version: "1"
    secretKey: password
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsecretsmanager-secretstore
  target:
    name: serveur-key
