apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-frontend
spec:
  selector:
    app: {{ .Release.Name }}-api-frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
