apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-api-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.static_ip_name }}
    networking.gke.io/managed-certificates: {{ .Release.Name }}-api-certificate
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - host: {{ .Values.mcrt_domain }}
      http:
        paths:
          - path: /api
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-api-ep
                port:
                  number: 80
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-api-frontend
                port:
                  number: 80

