apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-ep
spec:
  selector:
    app: {{ .Release.Name }}-api-ep
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
