apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-appender
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-appender
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-appender
    spec:
      containers:
        - name: {{ .Release.Name }}-appender
          image: "{{ .Values.docker_image_location }}:{{ .Values.docker_image_tag }}"
          env:
            - name: GENEGRAPH_PLATFORM
              value: {{ .Values.platform }}
            - name: GENEGRAPH_FUNCTION
              value: appender
          ports:
            - name: genegraph-port
              containerPort: 8888
          readinessProbe:
            httpGet:
              path: /ready
              port: genegraph-port
          resources:
            requests:
              memory: "2Gi"
              cpu: "100m"
            limits:
              memory: "2Gi"
