apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: genegraph-gene-validity
  template:
    metadata:
      labels:
        app: genegraph-gene-validity
    spec:
      volumes:
        - name: tdb-volume
          emptyDir:
            sizeLimit: 50Gi
      containers:
        - name: genegraph-gene-validity
          image: "us-east1-docker.pkg.dev/clingen-dev/genegraph-docker-repo/genegraph-gene-validity:{{ .Values.docker_image_tag }}"
          volumeMounts:
            - mountPath: /data
              name: tdb-volume
          ports:
            - name: genegraph-port
              containerPort: 8888
          readinessProbe:
            httpGet:
              path: /ready
              port: genegraph-port
          resources:
            requests:
              memory: "3Gi"
              cpu: "1000m"
            limits:
              memory: "10Gi"
