apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dev-transformer
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-dev-transformer
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-dev-transformer
    spec:
      volumes:
        - name: local-volume
          emptyDir:
            sizeLimit: 50Gi
      containers:
        - name: {{ .Release.Name }}-dev-transformer
          image: "{{ .Values.docker_image_location }}:{{ .Values.docker_image_tag }}"
          env:
            - name: GENEGRAPH_PLATFORM
              value: {{ .Values.platform }}
            - name: GENEGRAPH_FUNCTION
              value: dev-transform-curations
          volumeMounts:
            - mountPath: /data
              name: local-volume
          ports:
            - name: genegraph-port
              containerPort: 8888
          readinessProbe:
            httpGet:
              path: /ready
              port: genegraph-port
          resources:
            requests:
              memory: "2Gi"
              cpu: "200m"
            limits:
              memory: "2Gi"
