apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dev-graphql-endpoint
spec:
  replicas: {{ .Values.graphql_endpoint_replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: {{ .Release.Name }}-dev-graphql-endpoint
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-dev-graphql-endpoint
    spec:
      volumes:
        - name: local-volume
          emptyDir:
            sizeLimit: 100Gi
      containers:
        - name: {{ .Release.Name }}-dev-graphql-endpoint
          image: "{{ .Values.docker_image_location }}:{{ .Values.docker_image_tag }}"
          env:
            - name: GENEGRAPH_PLATFORM
              value: {{ .Values.platform }}
            - name: GENEGRAPH_FUNCTION
              value: dev-graphql-endpoint
          volumeMounts:
            - mountPath: /data
              name: local-volume
          ports:
            - name: genegraph-port
              containerPort: 8888
          readinessProbe:
            httpGet:
              path: /ready
              port: genegraph-port
          resources:
            requests:
              memory: "8Gi"
              cpu: "500m"
            limits:
              memory: "8Gi"
