apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-graphql-endpoint
spec:
  selector:
    app: {{ .Release.Name }}-graphql-endpoint
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
