apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include  "clinvar-combined.chartLabels" . | nindent 4 }}
spec:
  serviceName: "{{ .Release.Name }}-svc"
  selector:
    matchLabels:
      {{- include "clinvar-combined.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "clinvar-combined.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 600
      volumes:
        - name: {{ .Release.Name }}-vol
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc
      containers:
        - image: "{{ .Values.clinvar_streams_docker_image_name }}:{{ .Values.clinvar_streams_docker_image_tag }}"
          imagePullPolicy: {{ .Values.clinvar_streams_image_pull_policy }}
          name: clinvar-combiner
          {{- with .Values.clinvar_streams_deployment_resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: {{ .Release.Name }}-vol
              mountPath: "/data/"
          env:
            - name: SQLITE_DB
              value: "/data/clinvar.sqlite3"
            - name: DX_CV_SNAPSHOT_BUCKET
              value: {{ .Values.clinvar_combiner_snapshot_bucket }}
            - name: DX_CV_COMBINER_SNAPSHOT_VERSION
              value: {{ .Values.clinvar_combiner_snapshot_version }}
            - name: DX_CV_COMBINER_MODE
              value: {{ .Values.clinvar_combiner_mode }}
            - name: DX_CV_COMBINER_INPUT_TOPIC
              value: {{ .Values.clinvar_combiner_input_topic }}
            - name: DX_CV_COMBINER_OUTPUT_TOPIC
              value: {{ .Values.clinvar_combiner_output_topic }}
            - name: KAFKA_USER
              valueFrom:
                secretKeyRef:
                  name: dx-creds-{{ .Release.Name }}
                  key: kafka_user
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dx-creds-{{ .Release.Name }}
                  key: kafka_password
            - name: KAFKA_GROUP
              value: "{{ .Values.clinvar_streams_kafka_group }}"
          args:
            - clinvar-combiner
          ports:
            - containerPort: 8080
              name: service-port
          lifecycle:
            preStop:
              httpGet:
                # host defaults to pod IP
                path: "PreStop"
                port: 8080
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
  labels:
    {{- include  "clinvar-combined.chartLabels" . | nindent 4 }}
spec:
  storageClassName: {{ .Release.Name }}-storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
