apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: dx-creds-{{ .Release.Name }}
  labels:
    {{- include  "clinvar-combined.chartLabels" . | nindent 4 }}
spec:
  backendType: gcpSecretsManager
  projectId: {{ .Values.project_id }}
  data:
    - key: dx-creds
      property: kafka_user
      name: kafka_user
      version: latest
    - key: dx-creds
      property: kafka_password
      name: kafka_password
      version: latest
