apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-svc"
  labels:
    {{- include  "clinvar-combined.chartLabels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "clinvar-combined.selectorLabels" . | nindent 4 }}
