apiVersion: apps/v1
kind: Deployment
metadata:
  name: anyvar
  labels:
    app: anyvar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anyvar
  template:
    metadata:
      labels:
        app: anyvar
    spec:
      nodeSelector:
        cloud.google.com/gke-local-ssd: "true"
      volumes:
        - name: local-ssd
          hostPath:
            path: "/mnt/disks/ssd0/seqrepo"
      # https://kubernetes.io/docs/concepts/workloads/pods/init-containers/
      initContainers:
        # seqrepo by default will populate whatever device is at /usr/local/share/seqrepo
        - image: biocommons/seqrepo:2020-04-13
          imagePullPolicy: Always
          name: seqrepo
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 256Mi
              cpu: 0.2
          volumeMounts:
            - name: local-ssd
              mountPath: "/usr/local/share/seqrepo"
      containers:
        - image: redis:latest
          imagePullPolicy: Always
          name: redis
          ports:
            - containerPort: 6379
              name: redis
          resources:
            limits:
              memory: 512Mi
              cpu: 0.1

        - image: gcr.io/clingen-dev/anyvar:latest
          imagePullPolicy: Always
          name: anyvar
          ports:
            - containerPort: 5000
              name: anyvar
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 128Mi
              cpu: 0.2
          volumeMounts:
            - name: local-ssd
              mountPath: "/usr/local/share/seqrepo"
          env:
            - name: GA4GH_VRS_DATAPROXY_URI
              # Based on biocommons/seqrepo container version
              value: "seqrepo+file:///usr/local/share/seqrepo/2020-04-13"
            - name: ANYVAR_STORAGE_URI
              # Containers in pod share network namespace
              value: "localhost:6379"
