apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinvar-raw
  labels:
    app: clinvar-raw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clinvar-raw
  template:
    metadata:
      labels:
        app: clinvar-raw
    spec:
      containers:
        - image: gcr.io/clingen-dev/clinvar-raw:1.0
          imagePullPolicy: Always
          name: clinvar-raw
          env:
            - name: KAFKA_USER
              valueFrom:
                secretKeyRef:
                  name: clinvar-raw-credentials
                  key: user
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: clinvar-raw-credentials
                  key: password
