apiVersion: apps/v1
kind: Deployment
metadata:
  name: genegraph
  labels:
    app: genegraph
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: genegraph
  template:
    metadata:
      labels:
        app: genegraph
    spec:
      nodeSelector:
        cloud.google.com/gke-local-ssd: "true"
      volumes:
        - name: genegraph-vol
          hostPath:
            path: "/mnt/disks/ssd0"
      containers:
        - image: gcr.io/clingen-dev/genegraph:v18
          imagePullPolicy: Always
          name: genegraph  
          env:
            - name: GENEGRAPH_DATA_PATH
              value: "/data/"
            - name: GENEGRAPH_DATA_VERSION
              value: "2020-06-08T1603"
            - name: SERVEUR_KEY_PASS
              valueFrom:
                secretKeyRef:
                  name: serveur-key-pass
                  key: password
            - name: SERVEUR_KEYSTORE
              value: "/keys/dev.serveur.keystore.jks"
            - name: SERVEUR_TRUSTSTORE
              value: "/keys/serveur.truststore.jks"
            - name: CG_SEARCH_TOPICS
              value: "gene-dosage-stage;actionability;gci-legacy"
            - name: KAFKA_USER
              valueFrom:
                secretKeyRef:
                  name: kafka-credentials
                  key: user
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-credentials
                  key: password
            - name: DX_STAGE_JAAS
              value: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"$(KAFKA_USER)\" password=\"$(KAFKA_PASSWORD)\";"
            - name: GENEGRAPH_BUCKET
              value: genegraph-dev
          ports:
            - containerPort: 8888
              name: genegraph
          volumeMounts:
            - name: genegraph-vol
              mountPath: /data/

