apiVersion: v1
kind: Service
metadata:
  labels:
    app: seqrepo-service
  name: seqrepo-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: seqrepo-rest

