#!/bin/zsh
set -xeuo pipefail

input_topic=broad-dsp-clinvar
output_topic=clinvar-raw
cluster=clingen-prod
group=clinvar-raw-prod
cluster_id=$(confluent kafka cluster list | grep $cluster | awk '{print $1}')

kafka_properties_file=./kafka-prod.properties
if [[ ! -f "$kafka_properties_file" ]]; then
  echo "Kafka properties file not found: $kafka_properties_file "
  exit 1
fi

# reset offset on input topic
function topic_offset_to_zero {
    topic=$1
    group=$2
    kafka-consumer-groups --command-config ${kafka_properties_file} \
      --bootstrap-server pkc-4yyd6.us-east1.gcp.confluent.cloud:9092 \
      --reset-offsets \
      --to-offset 0 \
      --group "$group" \
      --topic "$topic" \
      --timeout 10000 \
      --execute
}

echo "Resetting input topic offset"
topic_offset_to_zero $input_topic $group

echo "Deleting and recreating output topic"
# leave +e untoggled so topic deletes are allowed to fail
set +e
confluent kafka topic delete --cluster $cluster_id $output_topic
sleep 3
set -e

# switch -e so exits on failure
confluent kafka topic create --cluster $cluster_id $output_topic \
  --partitions 1 \
  --config retention.ms=-1
