apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://35.237.22.18
        targetRevision: 0.5.7
        project: 'dev'
      # - cluster: stage
      #   url: https://35.185.65.146
      #   targetRevision: 0.5.7
      #   project: 'stage'
      # - cluster: prod
      #   url: https://kubernetes.default.svc
      #   targetRevision: 0.5.7
      #   project: 'prod'
  template:
    metadata:
      name: '{{cluster}}-external-secrets'
      labels:
        deployment: bootstrap
    spec:
      project: '{{project}}'
      source:
        chart: external-secrets
        repoURL: https://charts.external-secrets.io
        targetRevision: '{{targetRevision}}'
        helm:
          releaseName: external-secrets
          values: |
            replicaCount: 0
            resources:
              requests:
                cpu: 100m
                memory: 100Mi
              limits:
                cpu: 250m
                memory: 256Mi
      destination:
        server: '{{url}}'
        namespace: external-secrets
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
