static_ip_name: &staticip global-prod-argocd-ip
managed_cert_name: &certname argocd-prod-certificate
argo_host_name: &argohost argocd.prod.clingen.app
argo_url: &argourl https://argocd.prod.clingen.app # sadly, we can't concat strings...

# values to pass on to the argocd subchart
argo-cd:
  installCRDs: false
  controller:
    logLevel: warn
    logFormat: json
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "384Mi"
  dex:
    resources:
      requests:
        cpu: "100m"
        memory: "64Mi"
      limits:
        cpu: "300m"
        memory: "128Mi"
  redis:
    resources:
      requests:
        cpu: "100m"
        memory: "64Mi"
      limits:
        cpu: "300m"
        memory: "128Mi"
  repoServer:
    logLevel: warn
    logFormat: json
    resources:
      requests:
        cpu: "100m"
        memory: "64Mi"
      limits:
        cpu: "300m"
        memory: "128Mi"
  server:
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"
    logLevel: warn
    logFormat: json
    service:
      namedTargetPort: false
      annotations:
        cloud.google.com/backend-config: '{"default": "argo-cloudarmor-config"}'
    ingress:
      enabled: true
      paths:
        - /*
      pathType: ImplementationSpecific
      hosts:
        - *argohost
      annotations:
        kubernetes.io/ingress.global-static-ip-name: *staticip
        networking.gke.io/managed-certificates: *certname
        kubernetes.io/ingress.class: "gce"
    extraArgs:
    - --insecure
    rbacConfig:
      policy.default: role:readonly
      policy.csv: |
        g, clingen-data-model:b/g-engineers, role:admin
    config:
      url: *argourl
      dex.config: |
        connectors:
          - type: github
            id: github
            name: GitHub
            config:
              clientID: 3b48211878f7a8ce54a0
              clientSecret: $dex.github.clientSecret
              orgs:
              - name: clingen-data-model
                teams:
                  - b/g-engineers
