apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage-clingen-clinvar-submitter
  namespace: argocd
spec:
  project: stage
  source:
    repoURL: https://github.com/clingen-data-model/architecture.git
    targetRevision: HEAD
    path: helm/charts/clingen-clinvar-submitter
    helm:
      valueFiles:
      - ../../values/clinvar-submitter/values-stage.yaml
  destination:
    server: https://35.229.71.111
    namespace: submitter
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
