apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage-genegraph
  namespace: argocd
spec:
  project: stage
  source:
    repoURL: https://github.com/clingen-data-model/architecture.git
    targetRevision: HEAD
    path: helm/charts/clingen-genegraph
    helm:
      releaseName: genegraph 
      valueFiles:
      - ../../values/genegraph/values-stage.yaml
  destination:
    server: https://35.237.22.18
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
