apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage-secrets
  namespace: argocd
spec:
  project: stage
  source:
    repoURL: https://github.com/clingen-data-model/architecture.git
    targetRevision: HEAD
    path: services/stage/secrets
  destination:
    server: https://35.185.65.146
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
