project_id: clingen-dev
clinvar_streams_docker_image_name: gcr.io/clingen-dev/clinvar-streams
clinvar_streams_docker_image_tag: latest
clinvar_raw_input_topic: broad-dsp-clinvar-dev
clinvar_raw_output_topic: clinvar-raw-dev
clinvar_streams_kafka_group: clinvar-raw-dev
clinvar_streams_container_args:
  - clinvar-raw
