project_id: clingen-dx
clinvar_streams_docker_image_name: gcr.io/clingen-dx/clinvar-streams
clinvar_streams_docker_image_tag: prod-deploy
clinvar_raw_input_topic: broad-dsp-clinvar
clinvar_raw_output_topic: clinvar-raw
clinvar_streams_kafka_group: clinvar-raw-prod
clinvar_streams_container_args:
  - clinvar-raw
