apiVersion: v1
kind: Service
metadata:
  labels:
    app: clingen-kb
  name: clingen-kb
spec:
  type: LoadBalancer
  loadBalancerIP: 34.73.231.26
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: clingen-kb
  
