apiVersion: apps/v1
kind: Deployment
metadata:
  name: clingen-kb
  labels:
    app: clingen-kb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clingen-kb
  template:
    metadata:
      labels:
        app: clingen-kb
    spec:
      containers:
        - image:
            gcr.io/clingen-stage/clingen-knowledge:v5
          name: clingen-kb
          resources:
            limits:
              memory: 2Gi
            requests:
              memory: 1Gi
          env:
            - name: NEO4J_URL
              valueFrom:
                secretKeyRef:
                  name: neo4j-url
                  key: url
          ports:
            - containerPort: 80
              name: clingen-kb
