apiVersion: batch/v1
kind: Job
metadata:
  name: genegraph-migration
  labels:
    app: genegraph
spec:
  template:
    metadata:
      labels:
        app: genegraph
    spec:
      nodeSelector:
        cloud.google.com/gke-local-ssd: "true"
      volumes:
        - name: genegraph-vol
          hostPath:
            path: "/mnt/disks/ssd0"
      containers:
        - image: gcr.io/clingen-stage/genegraph:f28839d0ab4a65e3a9a77fee3bc9c163338a7f8b
          name: genegraph
          env:
            - name: GENEGRAPH_DATA_PATH
              value: "/data/"
            - name: GENEGRAPH_DATA_VERSION
              value: "2020-09-30T2041"
            - name: SERVEUR_KEY_PASS
              valueFrom:
                secretKeyRef:
                  name: serveur-key-pass
                  key: password
            - name: CG_SEARCH_TOPICS
              value: "actionability;gci-legacy;gene-dosage-stage"
            - name: GENEGRAPH_MODE
              value: "production"
            - name: GENEGRAPH_BUCKET
              value: "genegraph-stage"
            - name: GENEGRAPH_GQL_CACHE
              value: "true"
            - name: GENEGRAPH_VALIDATE_EVENTS
              value: "true"
            - name: GENEGRAPH_RESPONSE_CACHE
              value: "true"
            - name: DX_STAGE_JAAS
              valueFrom:
                secretKeyRef:
                  name: dx-stage-jaas
                  key: password
          ports:
            - containerPort: 8888
              name: genegraph
          volumeMounts:
            - name: genegraph-vol
              mountPath: /data/
          command: ["java", "-jar", "/app/app.jar", "migration"]
      restartPolicy: "OnFailure"
