apiVersion: apps/v1
kind: Deployment
metadata:
  name: genegraph
  labels:
    app: genegraph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genegraph
  template:
    metadata:
      labels:
        app: genegraph
    spec:
      nodeSelector:
        cloud.google.com/gke-local-ssd: "true"
      volumes:
        - name: genegraph-vol
          hostPath:
            path: "/mnt/disks/ssd0"
      containers:
        - image: gcr.io/clingen-stage/genegraph:fb536f9ab851d3cdf6c030582f26073e1b5d0d95
          name: genegraph
          env:
            - name: GENEGRAPH_DATA_VOL
              value: "/data/"
            - name: GENEGRAPH_DATA_VERSION
              value: "2020-07-01T2112"
            - name: SERVEUR_KEY_PASS
              valueFrom:
                secretKeyRef:
                  name: serveur-key-pass
                  key: password
            - name: CG_SEARCH_TOPICS
              value: "actionability;gci-legacy;gene-dosage-stage"
            - name: GENEGRAPH_MODE
              value: "production"
            - name: GENEGRAPH_BUCKET
              value: "genegraph-stage"
            - name: GENEGRAPH_GQL_CACHE
              value: "true"
            - name: DX_STAGE_JAAS
              valueFrom:
                secretKeyRef:
                  name: dx-stage-jaas
                  key: password
          ports:
            - containerPort: 8888
              name: genegraph
          volumeMounts:
            - name: genegraph-vol
              mountPath: /data/

              
  

