apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j
spec:
  selector:
    matchLabels:
      app: neo4j
  serviceName: "neo4j"
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
      - name: neo4j
        image: neo4j:3.4
        resources:
          requests:
            memory: 6Gi
            cpu: 500m
          limits:
            memory: 10Gi
        env:
          - name: NEO4J_dbms_memory_heap_initial__size
            value: 3500m
          - name: NEO4J_dbms_memory_heap_max__size
            value: 3500m
          - name: NEO4J_dbms_memory_pagecache_size
            value: 2000m
        ports:
        - containerPort: 7474
          name: neo4j-http
        - containerPort: 7687
          name: neo4j-bolt
        volumeMounts:
        - name: neo4j-pvc
          mountPath: "/data"
  volumeClaimTemplates:
  - metadata:
      name: neo4j-pvc
    spec:
      storageClassName: faster
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 30Gi

# dbms.memory.heap.initial_size=3500m
# dbms.memory.heap.max_size=3500m
# dbms.memory.pagecache.size=2000m
