apiVersion: v1
kind: ConfigMap
metadata:
  name: bigqueryrc-{{ .Release.Name }}
  labels:
    {{- include "clingen-clinvar-ingest-updater.labels" . | nindent 4 }}
data:
  bigquery.rc: |
    credential_file = /root/.config/gcloud/legacy_credentials/{{ .Values.service_account_name }}@{{ .Values.project_name }}.iam.gserviceaccount.com/singlestore_bq.json
    project_id = {{ .Values.project_name }}
