apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "clingen-clinvar-ingest-updater.fullname" . }}
  labels:
    {{- include "clingen-clinvar-ingest-updater.labels" . | nindent 4 }}
spec:
  schedule: "0 */4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: google-cloud-key
              secret:
                secretName: google-account-key-{{ .Release.Name }}
            - name: bigqueryrc
              configMap:
                name: bigqueryrc-{{ .Release.Name }}
          containers:
          - name: hello
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: Always
            volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
            - name: bigqueryrc
              mountPath: /root/.bigqueryrc
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            command:
            - /bin/sh
            - -c
            - /usr/local/bin/sync.sh
          restartPolicy: OnFailure
