apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: google-account-key-{{ .Release.Name }}
  labels:
    {{- include "clingen-clinvar-ingest-updater.labels" . | nindent 4 }}
spec:
  backendType: gcpSecretsManager
  projectId: {{ .Values.project_id }}
  data:
    - key: {{ .Values.gcp_key_secret_name }}
      name: key.json
      version: latest
