---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: google-account-key-{{ .Release.Name }}
  labels:
    {{- include "clingen-clinvar-ingest-updater.labels" . | nindent 4 }}
spec:
  data:
  - remoteRef:
      key: {{ .Values.gcp_key_secret_name }}
      version: latest
    secretKey: key.json
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsecretsmanager-secretstore
  target:
    name: google-account-key-{{ .Release.Name }}
