genegraph_cg_search_topics: "gene-dosage-jira;actionability;gci-legacy"
genegraph_data_version: "2021-02-09T1847"
genegraph_docker_image_name: gcr.io/clingen-dev/genegraph
genegraph_docker_image_tag: v57
genegraph_gcs_bucket: genegraph-dev

genegraph_tls_cert: false

genegraph_image_version_envvar: true
genegraph_configure_pod_antiaffinity: true
genegraph_updateStrategy: true
genegraph_configureLivenessProbe: true

genegraph_gql_cache: false
genegraph_response_cache: false
