# cd architecture/helm
# helm template genegraph charts/clingen-genegraph -f values/genegraph/values-dev.yaml

# deployment
genegraph_docker_image_name: gcr.io/clingen-dev/genegraph
genegraph_docker_image_tag: c5f9234c406323669850c85cb5e9fb91e98512b9
genegraph_image_version_envvar: true
genegraph_data_version: "2021-11-17T1900"
genegraph_cg_search_topics: "actionability;gci-legacy;gene-dosage-jira-clone"
genegraph_gcs_bucket: genegraph-dev
genegraph_gql_cache: true
genegraph_response_cache: true
# certificate and ingress
genegraph_mcrt_domains:
  - 'genegraph-dev.clingen.app'
genegraph_static_ip_name: global-dev-genegraph-dev-ip

# service
# node port
#genegraph_service_type: NodePort
#genegraph_port: 8888
# load balancer
# genegraph_service_lb_ip: 35.227.247.152

# run migration job before deployment
genegraph_run_migration: true
