# cd architecture/helm
# helm template genegraph charts/clingen-genegraph -f values/genegraph/values-dev.yaml

# deployment
genegraph_docker_image_name: gcr.io/clingen-dev/genegraph
genegraph_docker_image_tag: 8d7efb1d369afd237c8d3fb8e73187ce35a3a5ce
genegraph_image_version_envvar: true
genegraph_data_version: "2021-09-15T1200"
genegraph_cg_search_topics: "gene-dosage-jira;actionability;gci-legacy;gci-legacy-dev"
genegraph_gcs_bucket: genegraph-dev
genegraph_gql_cache: true
genegraph_response_cache: true

# certificate and ingress
genegraph_configure_ingress: false
genegraph_tls_cert: false
genegraph_mcrt_domains:
  - 'genegraph-dev.clingen.app'
genegraph_static_ip_name: global-dev-genegraph-dev-ip

# service
#genegraph_service_type: NodePort
#genegraph_port: 8888

# run migration job before deployment
genegraph_run_migration: true

