# cd architecture/helm
# helm template genegraph charts/clingen-genegraph -f values/genegraph/values-dev.yaml

# deployment
genegraph_docker_image_name: gcr.io/clingen-dev/genegraph
genegraph_docker_image_tag: 0ef4298a26c1e626c30af1cdd55a351d6b057593
genegraph_image_version_envvar: true
genegraph_data_version: "2022-05-24T1404"
#genegraph_migration_data_version: "2022-01-24T1352:764b4fd149e0e41c54c433e22d190d131cb151af"
genegraph_cg_search_topics: "gene-validity-dev;actionability;gene-dosage-jira"
#"gene-validity-raw;gci-legacy-report-only;actionability;gene-dosage-jira"
genegraph_gcs_bucket: genegraph-dev
genegraph_gql_cache: true
genegraph_response_cache: true
# certificate and ingress
genegraph_mcrt_domains:
  - 'genegraph-dev.clingen.app'
genegraph_static_ip_name: global-dev-genegraph-dev-ip
# run migration job before deployment
genegraph_run_migration: true
