# cd architecture/helm
# helm template genegraph charts/clingen-genegraph -f values/genegraph/values-dev.yaml

# deployment
genegraph_docker_image_name: gcr.io/clingen-dev/genegraph
genegraph_docker_image_tag: 1378af18ee1c8196f06acaba86edf8171fa8cf73
genegraph_image_version_envvar: true
genegraph_data_version: "2021-09-28T1601"
genegraph_cg_search_topics: "gene-dosage-jira;actionability;gci-legacy;gci-legacy-dev"
genegraph_gcs_bucket: genegraph-dev
genegraph_gql_cache: true
genegraph_response_cache: true
# certificate and ingress
genegraph_mcrt_domains:
  - 'genegraph-dev.clingen.app'
genegraph_static_ip_name: global-dev-genegraph-dev-ip
# service
# node port
#genegraph_service_type: NodePort
#genegraph_port: 8888
# load balancer
# genegraph_service_lb_ip: 35.227.247.152

# run migration job before deployment
genegraph_run_migration: false
