# cd architecture/helm
# helm template genegraph charts/clingen-genegraph -f values/genegraph/values-dev.yaml

# deployment
genegraph_docker_image_name: gcr.io/clingen-dev/genegraph
genegraph_docker_image_tag: 7b208033b537317a726d334c732ea37069af9dec
genegraph_image_version_envvar: true
genegraph_data_version: "2022-01-10T1300"
genegraph_migration_data_version: "2021-11-02T1858"
genegraph_cg_search_topics: "actionability;gci-legacy;gene-dosage-jira-clone;gci-legacy-dev"
genegraph_gcs_bucket: genegraph-dev
genegraph_gql_cache: true
genegraph_response_cache: true
# certificate and ingress
genegraph_mcrt_domains:
  - 'genegraph-dev.clingen.app'
genegraph_static_ip_name: global-dev-genegraph-dev-ip

# service
# node port
#genegraph_service_type: NodePort
#genegraph_port: 8888
# load balancer
# genegraph_service_lb_ip: 35.227.247.152

# run migration job before deployment
genegraph_run_migration: true
