# cd architecture/helm
# helm template genegraph charts/clingen-genegraph -f values/genegraph/values-dev.yaml

# deployment
genegraph_docker_image_name: gcr.io/clingen-dev/genegraph
genegraph_docker_image_tag: 81b49bc0ba07b8a8158457bf95b3f3c0a088e521
genegraph_image_version_envvar: true
genegraph_data_version: "2021-09-09T1213"
genegraph_cg_search_topics: "gene-dosage-jira;actionability;gci-legacy;gci-legacy-dev"
genegraph_gcs_bucket: genegraph-dev
genegraph_gql_cache: true
genegraph_response_cache: true

# certificate and ingress
genegraph_tls_cert: false
genegraph_mcrt_domains:
  - 'genegraph-dev.clingen.app'
genegraph_static_ip_name: global-dev-genegraph-dev-ip

# service
#genegraph_service_type: NodePort
#genegraph_port: 8888

# run migration job before deployment
genegraph_run_migration: false

