# cd architecture/helm
# helm template genegraph charts/clingen-genegraph -f values/genegraph/values-dev.yaml

# deployment
genegraph_docker_image_name: gcr.io/clingen-dev/genegraph
genegraph_docker_image_tag: 48791a23c1754f43f5905aaafc1c2df12888b8b3
genegraph_image_version_envvar: true
genegraph_data_version: "2022-04-20T1427"
#genegraph_migration_data_version: "2022-01-24T1352:764b4fd149e0e41c54c433e22d190d131cb151af"
genegraph_cg_search_topics: "actionability;gci-legacy;gene-dosage-jira"
genegraph_gcs_bucket: genegraph-dev
genegraph_gql_cache: true
genegraph_response_cache: true
# certificate and ingress
genegraph_mcrt_domains:
  - 'genegraph-dev.clingen.app'
genegraph_static_ip_name: global-dev-genegraph-dev-ip
# service
# node port
#genegraph_service_type: NodePort
#genegraph_port: 8888
# load balancer
# genegraph_service_lb_ip: 35.227.247.152

# run migration job before deployment
genegraph_run_migration: true
