# in order of appearance in the helm templates

# deployment
genegraph_update_strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 50%
    maxUnavailable: 50%
genegraph_pod_affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - topologyKey: kubernetes.io/hostname
      labelSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - genegraph
genegraph_docker_image_name: gcr.io/clingen-dev/genegraph
genegraph_docker_image_tag: v81
genegraph_image_version_envvar: true
genegraph_data_version: "2021-05-19T1221"
genegraph_cg_search_topics: "gene-dosage-jira;actionability;gci-legacy;gci-legacy-dev"
genegraph_gcs_bucket: genegraph-dev
genegraph_gql_cache: false
genegraph_response_cache: false

# certificate and ingress
genegraph_tls_cert: false
