# helm template genegraph charts/clingen-genegraph -f values/genegraph/values-stage.yaml

# deployment
genegraph_update_strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 50%
    maxUnavailable: 50%
genegraph_pod_affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: kubernetes.io/hostname
        labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - genegraph
genegraph_docker_image_name: gcr.io/clingen-stage/genegraph
genegraph_docker_image_tag: 4b79a01bcd459146ae33b7b9511a430e4776b1a0
genegraph_deployment_resources:
  requests:
    memory: 6Gi
    cpu: 1000m
  limits:
    memory: 10Gi
genegraph_image_version_envvar: true
genegraph_data_version: "2021-08-17T2022"
genegraph_cg_search_topics: "actionability;gci-legacy;gene-dosage-jira"
genegraph_gcs_bucket: genegraph-stage
genegraph_dx_jaas_secretname: dx-stage-jaas

# certificate and ingress
genegraph_tls_cert: false
genegraph_configure_ingress: false

# service
genegraph_service_type: LoadBalancer
genegraph_service_lb_ip: 34.74.244.24

# run migration job before deployment
genegraph_run_migration: true
