# in order of appearance in the helm templates
# deployment
genegraph_replicas: 2
genegraph_update_strategy: true
genegraph_configure_pod_antiaffinity: true
genegraph_docker_image_name: gcr.io/clingen-dx/genegraph
genegraph_docker_image_tag: 86a9b27faf2e6ebbc69143f0ae29bb948dbbe1c4
genegraph_deployment_resources:
  requests:
    memory: 6Gi
    cpu: 1000m
  limits:
    memory: 10Gi
genegraph_image_version_envvar: true
genegraph_data_version: "2021-04-02T0125"
genegraph_cg_search_topics: "actionability;gci-legacy;gene-dosage-jira"
genegraph_gcs_bucket: genegraph-prod
genegraph_dx_jaas_secretname: dx-stage-jaas
genegraph_configure_livenessProbe: true

# certificate and ingress
genegraph_tls_cert: false
genegraph_service: true
