# cd architecture/helm
# helm template genegraph charts/clingen-genegraph -f values/genegraph/values-dev.yaml

# deployment
genegraph_docker_image_name: gcr.io/clingen-dev/genegraph
genegraph_docker_image_tag: 353b22cde2f5b2af6e238f0b5bc9aac3b49cd85a
genegraph_image_version_envvar: true
genegraph_data_version: "2022-06-14T1449"
#genegraph_migration_data_version: "2022-01-24T1352:764b4fd149e0e41c54c433e22d190d131cb151af"
genegraph_cg_search_topics: "gene-validity-raw;gci-legacy-report-only;actionability;gene-dosage-jira"
genegraph_gcs_bucket: genegraph-dev
genegraph_gql_cache: true
genegraph_response_cache: true
# certificate and ingress
genegraph_mcrt_domains:
  - 'genegraph-dev.clingen.app'
genegraph_static_ip_name: global-dev-genegraph-dev-ip
# run migration job before deployment
genegraph_run_migration: true
