# helm template genegraph charts/clingen-genegraph -f values/genegraph/values-dev.yaml

# deployment

#genegraph_update_strategy:
#  type: RollingUpdate
#  rollingUpdate:
#    maxSurge: 50%
#    maxUnavailable: 50%
#genegraph_pod_affinity:
#  podAntiAffinity:
#    requiredDuringSchedulingIgnoredDuringExecution:
#    - topologyKey: kubernetes.io/hostname
#      labelSelector:
#        matchExpressions:
#        - key: app
#          operator: In
#          values:
#          - genegraph
genegraph_docker_image_name: gcr.io/clingen-dev/genegraph
genegraph_docker_image_tag: 8a93b3aad25fc9a6fb936c5d5a1db706ad2acba9
genegraph_image_version_envvar: true
genegraph_data_version: "2021-09-08T1752"
genegraph_cg_search_topics: "gene-dosage-jira;actionability;gci-legacy;gci-legacy-dev"
genegraph_gcs_bucket: genegraph-dev
genegraph_gql_cache: false
genegraph_response_cache: false

# certificate and ingress
genegraph_tls_cert: false
genegraph_mcrt_domains:
- 'genegraph-testing.clingen.app'
genegraph_static_ip_name: global-dev-genegraph-dev-ip

# service
genegraph_service_type: NodePort
genegraph_port: 8888

# run migration job before deployment
genegraph_run_migration: true

