# helm template genegraph charts/clingen-genegraph -f values/genegraph/values-prod.yaml

# in order of appearance in the helm templates
# deployment
genegraph_replicas: 2
genegraph_update_strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 50%
    maxUnavailable: 50%
genegraph_pod_affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: kubernetes.io/hostname
        labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
                - genegraph
genegraph_docker_image_name: gcr.io/clingen-dx/genegraph
genegraph_docker_image_tag: c5111f6f2d4adfce0f51e4d7873c318ef3a98fa1
genegraph_deployment_resources:
  requests:
    memory: 6Gi
    cpu: 1000m
  limits:
    memory: 10Gi
genegraph_image_version_envvar: true
genegraph_data_version: "2021-10-05T1916"
genegraph_cg_search_topics: "actionability;gci-legacy;gene-dosage-jira"
genegraph_gcs_bucket: genegraph-prod
genegraph_gql_logging_topic: genegraph_logs
genegraph_dx_jaas_secretname: dx-stage-jaas
# certificate and ingress
genegraph_mcrt_domains:
  - 'genegraph.prod.clingen.app'
genegraph_static_ip_name: global-prod-genegraph-prod-ip
# run migration job before deployment
genegraph_run_migration: false
