# helm template genegraph charts/clingen-genegraph -f values/genegraph/values-stage.yaml

# deployment
genegraph_update_strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 50%
    maxUnavailable: 50%
genegraph_pod_affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: kubernetes.io/hostname
        labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
                - genegraph
genegraph_docker_image_name: gcr.io/clingen-stage/genegraph
genegraph_docker_image_tag: 0bbbbf172a53cba3bea6d9eab357d32d12b32d98
genegraph_deployment_resources:
  requests:
    memory: 6Gi
    cpu: 1000m
  limits:
    memory: 10Gi
genegraph_image_version_envvar: true
genegraph_data_version: "2021-11-10T1344"
genegraph_cg_search_topics: "actionability;gci-legacy;gene-dosage-jira"
genegraph_gcs_bucket: genegraph-stage
genegraph_dx_jaas_secretname: dx-stage-jaas
# certificate and ingress
genegraph_mcrt_domains:
  - 'genegraph.stage.clingen.app'
genegraph_static_ip_name: clingen-ds-stage-ip
# run migration job before deployment
genegraph_run_migration: true
