apiVersion: apps/v1
kind: Deployment
metadata:
  name: clingen-kb
  labels:
    app: clingen-kb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clingen-kb
  template:
    metadata:
      labels:
        app: clingen-kb
    spec:
      containers:
        - image:
            gcr.io/clingen-dev/clingen-knowledge:v11
          imagePullPolicy: Always
          name: clingen-kb
          resources:
            limits:
              memory: 8Gi
            requests:
              memory: 6Gi
              cpu: 1000m
          env:
            - name: NEO4J_URL
              valueFrom:
                secretKeyRef:
                  name: neo4j-url
                  key: url
          ports:
            - containerPort: 80
              name: clingen-kb
