---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: clinvar-raw-producer-kafka-dev-password
spec:
  backendType: gcpSecretsManager
  projectId: clingen-dev
  data:
    - key: clinvar-raw-producer-kafka-dev-password
      name: kafka-dev-pass.txt
      version: latest
