---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: clinvar-submissions-credentials
spec:
  backendType: gcpSecretsManager
  projectId: clingen-dev
  data:
    - key: clinvar-submissions-credentials
      name: password
      property: password
      version: latest
    - key: clinvar-submissions-credentials
      name: user
      property: user
      version: latest
