---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: clinvar-raw-producer-kafka-dev-user
spec:
  data:
  - remoteRef:
      key: clinvar-raw-producer-kafka-dev-user
      version: latest
    secretKey: kafka-dev-user.txt
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsecretsmanager-secretstore
  target:
    name: clinvar-raw-producer-kafka-dev-user
