---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dx-dev-jaas
spec:
  data:
  - remoteRef:
      key: dx-dev-jaas
      version: latest
    secretKey: password
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsecretsmanager-secretstore
  target:
    name: dx-dev-jaas
