---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: dx-migration-credentials
spec:
  backendType: gcpSecretsManager
  projectId: clingen-dev
  data:
    - key: dx-migration-credentials
      name: destination_pass
      property: destination_pass
      version: latest
    - key: dx-migration-credentials
      name: destination_user
      property: destination_user
      version: latest
    - key: dx-migration-credentials
      name: key_pass
      property: key_pass
      version: latest
    - key: dx-migration-credentials
      name: keystore_pass
      property: keystore_pass
      version: latest
    - key: dx-migration-credentials
      name: truststore_pass
      property: truststore_pass
      version: latest
