---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dx-migration-credentials
spec:
  data:
  - remoteRef:
      key: dx-migration-credentials
      property: destination_pass
      version: latest
    secretKey: destination_pass
  - remoteRef:
      key: dx-migration-credentials
      property: destination_user
      version: latest
    secretKey: destination_user
  - remoteRef:
      key: dx-migration-credentials
      property: key_pass
      version: latest
    secretKey: key_pass
  - remoteRef:
      key: dx-migration-credentials
      property: keystore_pass
      version: latest
    secretKey: keystore_pass
  - remoteRef:
      key: dx-migration-credentials
      property: truststore_pass
      version: latest
    secretKey: truststore_pass
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsecretsmanager-secretstore
  target:
    name: dx-migration-credentials
