---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: dx-prod-jaas
spec:
  backendType: gcpSecretsManager
  projectId: clingen-dev
  data:
    - key: dx-prod-jaas
      name: password
      version: latest
