---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: gene-dosage-jira-credentials
spec:
  backendType: gcpSecretsManager
  projectId: clingen-dev
  data:
    - key: gene-dosage-jira-credentials
      name: password
      property: password
      version: latest
    - key: gene-dosage-jira-credentials
      name: user
      property: user
      version: latest
