---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gene-dosage-jira-credentials
spec:
  data:
  - remoteRef:
      key: gene-dosage-jira-credentials
      property: password
      version: latest
    secretKey: password
  - remoteRef:
      key: gene-dosage-jira-credentials
      property: user
      version: latest
    secretKey: user
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsecretsmanager-secretstore
  target:
    name: gene-dosage-jira-credentials
