---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: serveur-key-pass
spec:
  data:
  - remoteRef:
      key: serveur-key-pass
      version: latest
    secretKey: password
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsecretsmanager-secretstore
  target:
    name: serveur-key-pass
