apiVersion: batch/v1
kind: Job
metadata:
  name: genegraph-migration-gvdev
  labels:
    app: genegraph-migration-gvdev
spec:
  template:
    metadata:
      labels:
        app: genegraph-migration-gvdev
    spec:
      nodeSelector:
        cloud.google.com/gke-local-ssd: "true"
      volumes:
        - name: genegraph-vol
          hostPath:
            path: "/mnt/disks/ssd0"
      containers:
        - image: gcr.io/clingen-dev/genegraph:v97
          imagePullPolicy: Always
          name: genegraph
          env:
            - name: GENEGRAPH_DATA_PATH
              value: "/data/"
            # - name: GENEGRAPH_DATA_VERSION
            #   value: "DOESNT GET USED DURING MIGRATION"
            - name: CG_SEARCH_TOPICS
              value: "gene-validity-raw"
            - name: GENEGRAPH_MODE
              value: "production"
            - name: GENEGRAPH_BUCKET
              value: genegraph-dev
            - name: GENEGRAPH_GQL_CACHE
              value: "true"
            - name: GENEGRAPH_RESPONSE_CACHE
              value: "true"
            - name: GENEGRAPH_BATCH_EVENT_SOURCES
              value: "gci-express-json;gci-raw-snapshot"
            - name: DX_JAAS_CONFIG
              valueFrom:
                secretKeyRef:
                  name: dx-prod-jaas
                  key: password
          ports:
            - containerPort: 8888
              name: genegraph-port
          volumeMounts:
            - name: genegraph-vol
              mountPath: /data/
          command: ["java", "-jar", "/app/app.jar", "migration"]
      restartPolicy: "OnFailure"
