# genegraph default chart values

# deployment
genegraph_replicas: 1
genegraph_revisionhistorylimit: 3
genegraph_update_strategy: {}
genegraph_pod_affinity: {}
genegraph_docker_image_name: gcr.io/clingen-dev/genegraph
genegraph_docker_image_tag: latest
genegraph_image_pull_policy: Always
genegraph_deployment_resources: {}
genegraph_image_version_envvar: false
genegraph_mode: production
genegraph_gcs_bucket: fake-bucket
genegraph_gql_cache: true
genegraph_validate_events: false
genegraph_response_cache: true
genegraph_gql_logging_topic:
# genegraph_experimental_schema:
genegraph_dx_jaas_secretname: dx-prod-jaas
genegraph_readiness_probe_path: /ready
genegraph_readiness_probe:
  periodSeconds: 30
  successThreshold: 1
  httpGet:
    path: /ready
    port: genegraph-port
genegraph_liveness_probe:
  periodSeconds: 30
  successThreshold: 1
  httpGet:
    path: /live
    port: genegraph-port
genegraph_batch_event_sources: gci-express-json;gci-neo4j-archive;gene-dosage-restored

# certificate and ingress
genegraph_configure_ingress: true
genegraph_tls_cert: true
genegraph_mcrt_domains:
  - 'genegraph-override-this.clingen.app'
genegraph_static_ip_name: override-this-static-ip


# service
genegraph_service: true
genegraph_service_type: NodePort
genegraph_port: 80

# storage
genegraph_local_ssd: true
genegraph_configure_storageclass: true

# run migration job before deployment
genegraph_run_migration: false

# redis cache
# Starts a redis instance as part of a helm chart
genegraph_start_redis: false
genegraph_redis_image: redis:7.0
# If host is defined, will pass the environment variable CACHE_REDIS_URI
# And the genegraph application will use that redis host for caching.
# genegraph_redis_host: <>
# genegraph_redis_port: 6379
