# genegraph default chart values

# deployment
genegraph_replicas: 1
genegraph_revisionhistorylimit: 3
genegraph_update_strategy: {}
genegraph_pod_affinity: {}
genegraph_docker_image_name: gcr.io/clingen-dev/genegraph
genegraph_docker_image_tag: latest
genegraph_image_pull_policy: Always
genegraph_deployment_resources: {}
genegraph_image_version_envvar: false
genegraph_mode: production
genegraph_gcs_bucket: 
genegraph_gql_cache: true
genegraph_validate_events: false
genegraph_response_cache: true
genegraph_gql_logging_topic: 
genegraph_dx_jaas_secretname: dx-prod-jaas
genegraph_readiness_probe_path: /ready
genegraph_readiness_probe:
  periodSeconds: 30
  successThreshold: 1
  httpGet:
    path: /ready
    port: genegraph-port
genegraph_liveness_probe:
  periodSeconds: 30
  successThreshold: 1
  httpGet:
    path: /live
    port: genegraph-port
genegraph_batch_event_sources: gci-express-json;gci-neo4j-archive;gene-dosage-restored

# certificate and ingress
genegraph_configure_ingress: true 
genegraph_tls_cert: true
genegraph_mcrt_domains:
  - 'genegraph-override-this.clingen.app'
genegraph_static_ip_name: override-this-static-ip


# service
genegraph_service: true
genegraph_service_type: NodePort
genegraph_port: 80

# storage
genegraph_local_ssd: true 
genegraph_configure_storageclass: true

# run migration job before deployment
genegraph_run_migration: false

