genegraph_deployment_resources: false
genegraph_dx_jaas_secretname: dx-prod-jaas
genegraph_image_pull_policy: Always
genegraph_mode: production
genegraph_validate_events: false

genegraph_tls_cert: false

clinvar_genegraph_deployment: false

gvdev_genegraph_deployment: false
