{{- if .Values.genegraph_service }}
apiVersion: v1
kind: Service
metadata:
  name: genegraph
  labels:
    app: genegraph
{{ include "clingen-genegraph.chartLabels" . | indent 4 }}
spec:
  type: LoadBalancer
  {{- if .Values.genegraph_service_lb_ip }}
  loadBalancerIP: {{ .Values.genegraph_service_lb_ip }}
  {{- end }}
  ports:
    - port: 80
      targetPort: 8888
      protocol: TCP
  selector:
    app: genegraph
{{- end}}
