apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    {{- include "clingen-genegraph.chartLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.genegraph_replicas }}
  {{- with .Values.genegraph_update_strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      {{- with .Values.genegraph_pod_affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      nodeSelector:
        cloud.google.com/gke-local-ssd: "true"
      volumes:
        - name: genegraph-vol
          hostPath:
            path: "/mnt/disks/ssd0/{{ .Release.Name }}"
      containers:
        - image: {{ .Values.genegraph_docker_image_name }}:{{ .Values.genegraph_docker_image_tag }}
          imagePullPolicy: {{ .Values.genegraph_image_pull_policy }}
          name: genegraph
          {{- with .Values.genegraph_deployment_resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- if .Values.genegraph_image_version_envvar }}
            - name: GENEGRAPH_IMAGE_VERSION
              value: "{{ .Values.genegraph_docker_image_name }}:{{ .Values.genegraph_docker_image_tag }}"
            {{- end }}
            - name: GENEGRAPH_DATA_PATH
              value: "/data/"
            - name: GENEGRAPH_DATA_VERSION
              value: {{ .Values.genegraph_data_version | quote }}
            {{- if .Values.genegraph_include_serveur_keypass }}
            - name: SERVEUR_KEY_PASS
              valueFrom:
                secretKeyRef:
                  name: serveur-key-pass
                  key: password
            {{- end }}
            - name: CG_SEARCH_TOPICS
              value: {{ .Values.genegraph_cg_search_topics | quote }}
            - name: GENEGRAPH_MODE
              value: {{ .Values.genegraph_mode | quote }}
            - name: GENEGRAPH_BUCKET
              value: {{ .Values.genegraph_gcs_bucket }}
            - name: GENEGRAPH_GQL_CACHE
              value: {{ .Values.genegraph_gql_cache | quote }}
            {{- if .Values.genegraph_validate_events }}
            - name: GENEGRAPH_VALIDATE_EVENTS
              value: "true"
            {{- end }}
            - name: GENEGRAPH_RESPONSE_CACHE
              value: {{ .Values.genegraph_response_cache | quote }}
            - name: DX_JAAS_CONFIG
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.genegraph_dx_jaas_secretname }}
                  key: password
          ports:
            - containerPort: 8888
              name: genegraph-port
          volumeMounts:
            - name: genegraph-vol
              mountPath: /data/
          {{- with .Values.genegraph_readiness_probe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.genegraph_liveness_probe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
