# Only run rsync when running a migration on stage
{{- if and (eq .Values.genegraph_run_migration true) (eq .Values.genegraph_gcs_bucket "genegraph-stage") }}
apiVersion: batch/v1
kind: Job
metadata:
  name:  {{ .Release.Name }}-rsync
  labels:
    app: {{ .Release.Name }}-rsync
    {{- include "clingen-genegraph.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: {{ .Release.Name }}-rsync
          image: 'gcr.io/cloud-builders/gsutil'
          command: ['gsutil', '-m', 'rsync', '-dru', 'gs://genegraph-stage/', 'gs://genegraph-prod']
      restartPolicy: "Never"
{{- end }}
