apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
{{ include "clingen-genegraph.chartLabels" . | indent 4 }}
spec:
  replicas: {{ .Values.genegraph_replicas }}
{{- if .Values.genegraph_updateStrategy }}
  strategy:
{{ include "clingen-genegraph.updateStrategy" . | indent 4 }}
{{- end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
{{- if .Values.genegraph_configure_pod_antiaffinity }}
{{ include "clingen-genegraph.podAntiAffinity" . | indent 6}}
{{- end }}
      nodeSelector:
        cloud.google.com/gke-local-ssd: "true"
      volumes:
        - name: genegraph-vol
          hostPath:
            path: {{ .Values.genegraph_volume_mountPath | quote }}
      containers:
        - image: {{ .Values.genegraph_docker_image_name }}:{{ .Values.genegraph_docker_image_tag }}
          imagePullPolicy: {{ .Values.genegraph_image_pull_policy }}
          name: genegraph
          {{- if .Values.genegraph_deployment_resources }}
          {{- with .Values.genegraph_deployment_resources }}
          resources:
            requests:
              {{- if .requests }}
              {{- range $key, $val := .requests }}
              {{ $key }}: {{ $val | quote }}
              {{- end }}
              {{- end }}
            limits:
              {{- if .limits }}
              {{- range $key, $val := .limits }}
              {{ $key }}: {{ $val | quote }}
              {{- end }}
              {{- end }}
          {{- end }}
          {{- end }}
          env:
            {{- if .Values.genegraph_image_version_envvar }}
            - name: GENEGRAPH_IMAGE_VERSION
              value: "{{ .Values.genegraph_docker_image_name }}:{{ .Values.genegraph_docker_image_tag }}"
            {{- end }}
            - name: GENEGRAPH_DATA_PATH
              value: "/data/"
            - name: GENEGRAPH_DATA_VERSION
              value: {{ .Values.genegraph_data_version | quote }}
            {{- if .Values.genegraph_include_serveur_keypass }}
            - name: SERVEUR_KEY_PASS
              valueFrom:
                secretKeyRef:
                  name: serveur-key-pass
                  key: password
            {{- end }}
            - name: CG_SEARCH_TOPICS
              value: {{ .Values.genegraph_cg_search_topics | quote }}
            - name: GENEGRAPH_MODE
              value: {{ .Values.genegraph_mode | quote }}
            - name: GENEGRAPH_BUCKET
              value: {{ .Values.genegraph_gcs_bucket }}
            - name: GENEGRAPH_GQL_CACHE
              value: {{ .Values.genegraph_gql_cache | quote }}
            {{- if .Values.genegraph_validate_events }}
            - name: GENEGRAPH_VALIDATE_EVENTS
              value: "true"
            {{- end }}
            - name: GENEGRAPH_RESPONSE_CACHE
              value: {{ .Values.genegraph_response_cache | quote }}
            - name: DX_JAAS_CONFIG
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.genegraph_dx_jaas_secretname }}
                  key: password
          ports:
            - containerPort: 8888
              name: genegraph-port
          volumeMounts:
            - name: genegraph-vol
              mountPath: /data/
          readinessProbe:
            periodSeconds: 30
            successThreshold: 1
            httpGet:
              path: {{ .Values.genegraph_readiness_probe_path }}
              port: genegraph-port
{{- if .Values.genegraph_configureLivenessProbe }}
{{ include "clingen-genegraph.livenessProbe" . | indent 10 }}
{{- end }}
