# Syncs the GCP secret named via .Values.genegraph_dx_jaas_secretname var and creates a secret in K8S
# called dx-jaas-releasename (replace releasename with your genegraph helm release name), with the secret
# value in a field called 'password'
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dx-jaas-{{ .Release.Name }}
  labels:
    {{- include "clingen-genegraph.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsecretsmanager-secretstore
  target:
    name: dx-jaas-{{ .Release.Name }}
  data:
  - secretKey: password
    remoteRef:
      key: {{ .Values.genegraph_dx_jaas_secretname }}
      version: latest
