{{- if .Values.genegraph_run_migration }}
apiVersion: batch/v1
kind: Job
metadata:
  name:  {{ .Release.Name }}-migration
  labels:
    app: {{ .Release.Name }}-migration
    {{- include "clingen-genegraph.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-migration
    spec:
      nodeSelector:
        {{- if .Values.genegraph_local_ssd }}
        cloud.google.com/gke-local-ssd: "true"
        {{- end }}
      volumes:
        {{- if .Values.genegraph_local_ssd }}
        - name: genegraph-vol
          hostPath:
            path: "/mnt/disks/ssd0/{{ .Release.Name }}-migration"
        {{- end }}
      containers:
        - image: {{ .Values.genegraph_docker_image_name }}:{{ .Values.genegraph_docker_image_tag }}
          imagePullPolicy: {{ .Values.genegraph_image_pull_policy }}
          name: genegraph
          env:
            - name: GENEGRAPH_DATA_VERSION
              value: "{{ .Values.genegraph_data_version }}:{{.Values.genegraph_docker_image_tag }}"
            - name: GENEGRAPH_DATA_PATH
              value: "/data/"
            - name: CG_SEARCH_TOPICS
              value: {{ .Values.genegraph_cg_search_topics | quote }}
            - name: GENEGRAPH_MODE
              value: {{ .Values.genegraph_mode | quote }}
            - name: GENEGRAPH_BUCKET
              value: {{ .Values.genegraph_gcs_bucket }}
            - name: GENEGRAPH_GQL_CACHE
              value: {{ .Values.genegraph_gql_cache | quote }}
            {{- if .Values.genegraph_validate_events }}
            - name: GENEGRAPH_VALIDATE_EVENTS
              value: "true"
            {{- end }}
            - name: GENEGRAPH_RESPONSE_CACHE
              value: {{ .Values.genegraph_response_cache | quote }}
            - name: GENEGRAPH_BATCH_EVENT_SOURCES
              value: {{ .Values.genegraph_batch_event_sources | quote }}
            - name: DX_JAAS_CONFIG
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.genegraph_dx_jaas_secretname }}
                  key: password
          ports:
            - containerPort: 8888
              name: genegraph-port
          volumeMounts:
          {{- if .Values.genegraph_local_ssd }}
            - name: genegraph-vol
              mountPath: /data/
          {{- end }}
          command: ["java", "-jar", "/app/app.jar", "migration"]
      restartPolicy: "Never"
{{- end }}
