{{- if .Values.genegraph_service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  annotations:
    {{- if .Values.genegraph_configure_ingress }}
    cloud.google.com/backend-config: '{"default": "{{ .Release.Name }}-backendconfig"}'
    {{- end }}
  labels:
    app: {{ .Release.Name }}
{{ include "clingen-genegraph.labels" . | indent 4 }}
spec:
  selector:
{{ include "clingen-genegraph.selectorLabels" . | indent 4 }}
  type: {{ .Values.genegraph_service_type }}
  {{- if .Values.genegraph_service_lb_ip }}
  loadBalancerIP: {{ .Values.genegraph_service_lb_ip }}
  {{- end }}
  ports:
    - port: {{ .Values.genegraph_port }}
      targetPort: 8888
      protocol: TCP
{{- end }}
