{{ if .Values.genegraph_persistent_disk }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
  labels:
    {{- include "clingen-genegraph.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Release.Name }}-faster
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.genegraph_persistent_disk.size }}
{{ end }}
