{{- if .Values.genegraph_configure_ingress }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  labels:
{{ include "clingen-genegraph.chartLabels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.genegraph_static_ip_name }}
    networking.gke.io/managed-certificates: {{ .Release.Name }}-certificate
    kubernetes.io/ingress.class: "gce"
spec:
  backend:
    serviceName: {{ .Release.Name }}
    servicePort: 8888
{{- end }}
