apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    {{- include "clingen-genegraph.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.genegraph_replicas }}
  revisionHistoryLimit: {{ .Values.genegraph_revisionhistorylimit }}
  {{- with .Values.genegraph_update_strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "clingen-genegraph.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
         {{- include "clingen-genegraph.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.genegraph_pod_affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      nodeSelector:
        {{- if .Values.genegraph_local_ssd }}
        cloud.google.com/gke-ephemeral-storage-local-ssd: "true"
        {{- end }}
      volumes:
        {{- if .Values.genegraph_local_ssd }}
        - name: genegraph-vol
          emptyDir:
            sizeLimit: 100Gi
        {{- else if .Values.genegraph_persistent_disk }}
        - name: genegraph-vol
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc
        {{- end }}
      containers:
        - image: {{ .Values.genegraph_docker_image_name }}:{{ .Values.genegraph_docker_image_tag }}
          imagePullPolicy: {{ .Values.genegraph_image_pull_policy }}
          name: genegraph
          {{- with .Values.genegraph_deployment_resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- if .Values.genegraph_image_version_envvar }}
            - name: GENEGRAPH_IMAGE_VERSION
              value: "{{ .Values.genegraph_docker_image_name }}:{{ .Values.genegraph_docker_image_tag }}"
            {{- end }}
            - name: GENEGRAPH_DATA_PATH
              value: "/data/"
            - name: GENEGRAPH_DATA_VERSION
              value: "{{ .Values.genegraph_data_version }}"
            {{- if .Values.genegraph_include_serveur_keypass }}
            - name: SERVEUR_KEY_PASS
              valueFrom:
                secretKeyRef:
                  name: serveur-key-pass
                  key: password
            {{- end }}
            - name: CG_SEARCH_TOPICS
              value: {{ .Values.genegraph_cg_search_topics | quote }}
            - name: GENEGRAPH_MODE
              value: {{ .Values.genegraph_mode | quote }}
            - name: GENEGRAPH_BUCKET
              value: {{ .Values.genegraph_gcs_bucket }}
            - name: GENEGRAPH_GQL_CACHE
              value: {{ .Values.genegraph_gql_cache | quote }}
            - name: GENEGRAPH_VALIDATE_EVENTS
              value: {{ .Values.genegraph_validate_events | quote }}
            - name: GENEGRAPH_RESPONSE_CACHE
              value: {{ .Values.genegraph_response_cache | quote }}
            {{- if .Values.genegraph_gql_logging_topic }}
            - name: GENEGRAPH_GQL_LOGGING_TOPIC
              value: {{.Values.genegraph_gql_logging_topic | quote }}
            {{- end }}
            {{- if .Values.genegraph_experimental_schema }}
            - name: GENEGRAPH_EXPERIMENTAL_SCHEMA
              value: {{.Values.genegraph_experimental_schema | quote }}
            {{- end }}
            {{- if .Values.genegraph_migration_data_version }}
            - name: GENEGRAPH_MIGRATION_VERSION
              value: {{ .Values.genegraph_migration_data_version | quote }}
            {{- end }}
            - name: GENEGRAPH_BATCH_EVENT_SOURCES
              value: {{ .Values.genegraph_batch_event_sources | quote }}
            {{- if .Values.genegraph_redis_host }}
            - name: CACHE_REDIS_URI
              value: redis://{{- tpl .Values.genegraph_redis_host . -}}:{{- .Values.genegraph_redis_port -}}
            {{- end }}
            {{- if .Values.genegraph_rocksdb_registry_uri }}
            - name: ROCKSDB_HTTP_URI
              value: {{ .Values.genegraph_rocksdb_registry_uri }}
            {{- end }}
            {{- if .Values.genegraph_rocksdb_http_start }}
            - name: ROCKSDB_HTTP_START
              value: "{{ .Values.genegraph_rocksdb_http_start }}"
            {{- end }}
            {{- if .Values.vrs_normalization_service }}
            - name: VARIATION_NORM_URL
              value: "{{ .Values.vrs_normalization_service }}"
            {{- end }}
            {{- if .Values.genegraph_nrepl_port }}
            - name: GENEGRAPH_NREPL_PORT
              value: "{{ .Values.genegraph_nrepl_port }}"
            {{- end }}
            - name: DX_JAAS_CONFIG
              valueFrom:
                secretKeyRef:
                  name: dx-jaas-{{ .Release.Name }}
                  key: password
          ports:
            - containerPort: 8888
              name: genegraph-port
            {{- if .Values.genegraph_rocksdb_http_start }}
            - containerPort: 6381
              name: vrs-cache-port
            {{- end }}
          volumeMounts:
          {{- if .Values.genegraph_local_ssd }}
            - name: genegraph-vol
              mountPath: /data/
          {{- else if .Values.genegraph_persistent_disk }}
            - name: genegraph-vol
              mountPath: /data/
          {{- end }}
          {{- if .Values.genegraph_command }}
          # Overrides the Docker image CMD
          command: {{ toYaml .Values.genegraph_command | nindent 12 }}
          {{- end}}
          {{- with .Values.genegraph_readiness_probe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.genegraph_liveness_probe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
