{{- if .Values.gvdev_genegraph_deployment }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gvdev_service_name }}
  labels:
    app: {{ .Values.gvdev_service_name }}
{{ include "clingen-genegraph.chartLabels" . | indent 4 }}
spec:
  selector:
    app: genegraph-gvdev
  type: NodePort
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
{{- end }}
