# ssd-storageclass.yaml
# https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/ssd-pd
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: faster
  labels:
{{ include "clingen-genegraph.chartLabels" . | indent 4 }}
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
