data:
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: 3b48211878f7a8ce54a0
          clientSecret: $dex.github.clientSecret
          orgs:
          - name: clingen-data-model
            teams:
              - b/g-engineers

