docker_image_tag: e5330c2d86e198715c22a656867c42b8eaa6c872
mcrt_domain: genegraph-gene-validity-dev.stage.clingen.app
static_ip_name: global-stage-dev-genegraph-gene-validity-ip
docker_image_location: "us-east1-docker.pkg.dev/clingen-stage/genegraph-stage/genegraph-gene-validity"
platform: dev
graphql_endpoint_replicas: 1
genegraph_namespace: genegraph-dev
