apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-clinvar-raw
  namespace: argocd
spec:
  project: dev
  source:
    repoURL: https://github.com/clingen-data-model/architecture.git
    targetRevision: HEAD
    path: helm/charts/clingen-raw-stream
    helm:
      releaseName: clinvar-raw
      valueFiles:
      - ../../values/clinvar-raw-stream/values-dev.yaml
  destination:
    server: https://35.237.22.18
    namespace: default
  syncPolicy:
