apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: variation-normalizer-vrs-2
  namespace: argocd
spec:
  project: dev
  source:
    repoURL: https://github.com/clingen-data-model/architecture.git
    targetRevision: master
    path: helm/charts/clingen-vicc
    helm:
      releaseName: varnorm-vrs-2
      valueFiles:
      - ../../values/clingen-vicc/values-vrs-2.yaml
  destination:
    server: https://35.237.22.18
    namespace: default
  syncPolicy:
