---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  annotations:
    {{- if .Values.anyvar_configure_ingress }}
    cloud.google.com/backend-config: '{"default": "{{ .Release.Name }}-backendconfig"}'
    {{- end }}
  labels:
    {{ include "clingen-anyvar.chartLabels" . | nindent 4 }}
spec:
  selector:
    {{ include "clingen-anyvar.selectorLabels" . | indent 4 }}
  type: NodePort
  ports:
    - port: {{ .Values.anyvar_port }}
      targetPort: 5000
      protocol: TCP
