########
# We are just running one instance of this now. If we decide to run more, some values
# may need to be split out into separate instance values files.
########


# postgres not exposed to internet, so password secrecy doesn't matter
uta_admin_password: uta_admin_pw

varnorm_container_port: 80

# External service
varnorm_external_service: true
varnorm_static_ip_name: global-variation-normalizer-dev-ip
varnorm_mcrt_domains:
  - normalization.clingen.app
