apiVersion: apps/v1
kind: Deployment
metadata:
  name: genegraph
  labels:
    app: genegraph
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: genegraph
  template:
    metadata:
      labels:
        app: genegraph
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app: genegraph
      nodeSelector:
        cloud.google.com/gke-local-ssd: "true"
      volumes:
        - name: genegraph-vol
          hostPath:
            path: "/mnt/disks/ssd0"
      containers:
        - image: gcr.io/clingen-stage/genegraph:5ca9a8a37787f75dc2db23f9fc0daa2f33b3644a
          name: genegraph
          resources:
            requests:
              memory: 6Gi
              cpu: 1000m
            limits:
              memory: 10Gi
          env:
            - name: GENEGRAPH_IMAGE_VERSION
              value: "gcr.io/clingen-stage/genegraph:5ca9a8a37787f75dc2db23f9fc0daa2f33b3644a"
            - name: GENEGRAPH_DATA_PATH
              value: "/data/"
            - name: GENEGRAPH_DATA_VERSION
              value: "2021-05-17T1615"
            - name: CG_SEARCH_TOPICS
              value: "actionability;gci-legacy;gene-dosage-jira"
            - name: GENEGRAPH_MODE
              value: "production"
            - name: GENEGRAPH_BUCKET
              value: "genegraph-stage"
            - name: GENEGRAPH_GQL_CACHE
              value: "true"
            # - name: GENEGRAPH_VALIDATE_EVENTS
            #   value: "true"
            - name: GENEGRAPH_RESPONSE_CACHE
              value: "true"
            - name: DX_JAAS_CONFIG
              valueFrom:
                secretKeyRef:
                  name: dx-stage-jaas
                  key: password
          ports:
            - containerPort: 8888
              name: genegraph-port
          volumeMounts:
            - name: genegraph-vol
              mountPath: /data/
          readinessProbe:
            periodSeconds: 30
            successThreshold: 1
            httpGet:
              path: /ready
              port: genegraph-port
          livenessProbe:
            periodSeconds: 30
            successThreshold: 1
            httpGet:
              path: /live
              port: genegraph-port
            

              
