apiVersion: batch/v1
kind: Job
metadata:
  name: genegraph-migration-stage
  labels:
    app: genegraph-migration-stage
spec:
  template:
    metadata:
      labels:
        app: genegraph-migration-stage
    spec:
      nodeSelector:
        cloud.google.com/gke-local-ssd: "true"
      volumes:
        - name: genegraph-vol
          hostPath:
            path: "/mnt/disks/ssd0"
      containers:
        - image: gcr.io/clingen-stage/genegraph:37ad117d73977364ecaffd6215ae10c9eb19e167
          imagePullPolicy: Always
          name: genegraph
          env:
            - name: GENEGRAPH_DATA_PATH
              value: "/data/"
            - name: CG_SEARCH_TOPICS
              value: "gene-dosage-jira;actionability;gci-legacy"
            - name: GENEGRAPH_MODE
              value: "production"
            - name: GENEGRAPH_BUCKET
              value: "genegraph-stage"
            - name: GENEGRAPH_GQL_CACHE
              value: "true"
            - name: GENEGRAPH_DATABASE_BUILD_MODE
              value: "true"
            - name: DX_JAAS_CONFIG
              valueFrom:
                secretKeyRef:
                  name: dx-stage-jaas
                  key: password
          ports:
            - containerPort: 8888
              name: genegraph
          volumeMounts:
            - name: genegraph-vol
              mountPath: /data/
          command: ["java", "-jar", "/app/app.jar", "migration"]
      restartPolicy: "OnFailure"
