apiVersion: batch/v1
kind: Job
metadata:
  name:  genegraph-rsync
  labels:
    app: genegraph-rsync
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: genegraph-rsync
          image: 'gcr.io/cloud-builders/gsutil'
          command: ['gsutil', '-m', 'rsync', '-dru', 'gs://genegraph-stage/', 'gs://genegraph-prod']
      restartPolicy: "Never"
