# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: genegraph-clinvar-service
#   name: genegraph-clinvar-service
# spec:
#   type: LoadBalancer
#   ports:
#     - port: 8888
#       targetPort: 8888
#       protocol: TCP
#   selector:
#     app: genegraph-clinvar
# ---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
    name: clingen-app-certificate
spec:
    domains:
    # - 'clingen.app'
    - 'genegraph-gvdev.clingen.app'
    # - '*.clingen.app'
---
apiVersion: v1
kind: Service
metadata:
    labels:
      app: genegraph-clinvar-service
    name: genegraph-clinvar-service
spec:
  selector:
    app: genegraph-clinvar
  type: NodePort
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: genegraph-clinvar-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: genegraph-clinvar-ip
    networking.gke.io/managed-certificates: clingen-app-certificate
    kubernetes.io/ingress.class: "gce"
spec:
  backend:
    serviceName: genegraph-clinvar-service
    servicePort: 8888
