apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
    name: clingen-app-certificate
spec:
    domains:
    # - 'clingen.app'
    - 'genegraph-dev.clingen.app'
    - 'genegraph-gvdev.clingen.app'
    # - '*.clingen.app'
