# in order of appearance in the helm templates
# deployment
genegraph_docker_image_name: gcr.io/clingen-dev/genegraph
genegraph_docker_image_tag: 597-all-clinvar-variations
genegraph_data_version: "2022-02-07T1753:25fb2b9d270ad4a7f7392b1cce0004dad4e0b21d"
genegraph_image_version_envvar: true
genegraph_cg_search_topics: "clinvar-raw"
genegraph_gcs_bucket: genegraph-dev
genegraph_gql_cache: false
genegraph_validate_events: false
genegraph_response_cache: false
genegraph_experimental_schema: true
genegraph_dx_jaas_secretname: dx-dev-jaas

# certificate and ingress
genegraph_configure_ingress: false
genegraph_tls_cert: false

# storage
genegraph_local_ssd: false
genegraph_configure_storageclass: true
genegraph_persistent_disk:
  size: 10Gi

# run migration job before deployment
genegraph_run_migration: false

# Use Redis
genegraph_start_redis: true
genegraph_redis_image: redis:7.0
# If genegraph_redis_host is defined, will pass the environment variable REDIS_CACHE_URI
# Host accepts a template. if genegraph_start_redis, the redis host
# will be the release name plus "-redis-svc"
genegraph_redis_host: "{{ .Release.Name }}-redis-svc"
genegraph_redis_port: 6379

genegraph_command: ["java", "-jar", "/app/app.jar", "vrs-cache"]
