# in order of appearance in the helm templates
# deployment
genegraph_docker_image_name: gcr.io/clingen-stage/genegraph
genegraph_docker_image_tag: stage-clinvar
genegraph_data_version: "2022-11-29T1939:77a4af4262d4a910cb53210d1b1796d0fbbdf1f7"
genegraph_image_version_envvar: true
genegraph_cg_search_topics: "clinvar-raw"
genegraph_gcs_bucket: genegraph-stage
genegraph_gql_cache: false
genegraph_validate_events: false
genegraph_response_cache: false
genegraph_experimental_schema: true
genegraph_dx_jaas_secretname: dx-stage-jaas

# certificate and ingress
genegraph_configure_ingress: false
genegraph_tls_cert: false

# storage
genegraph_local_ssd: false
genegraph_configure_storageclass: true
genegraph_persistent_disk:
  size: 10Gi

# run migration job before deployment
genegraph_run_migration: false

# Use Redis
genegraph_start_redis: true
genegraph_redis_image: redis:7.0
# If genegraph_redis_host is defined, will pass the environment variable REDIS_CACHE_URI
# Host accepts a template. if genegraph_start_redis, the redis host
# will be the release name plus "-redis-svc"
genegraph_redis_host: "{{ .Release.Name }}-redis-svc"
genegraph_redis_port: 6379

genegraph_command: ["java", "-jar", "/app/app.jar", "vrs-cache"]
