---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: argocd-dev-certificate
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
spec:
  domains:
  - '{{ .Values.argo_host_name }}'
