apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: argo-cloudarmor-config
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
spec:
  securityPolicy:
    name: "broad-cloud-armor"
