apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-genegraph
  namespace: argocd
spec:
  project: prod
  source:
    repoURL: https://github.com/clingen-data-model/architecture.git
    targetRevision: HEAD
    path: helm/charts/clingen-genegraph
    helm:
      releaseName: genegraph 
      valueFiles:
      - ../../values/genegraph/values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
