apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-clinvar-raw
  namespace: argocd
spec:
  project: prod
  source:
    repoURL: https://github.com/clingen-data-model/architecture.git
    targetRevision: HEAD
    path: helm/charts/clingen-raw-stream
    helm:
      releaseName: clinvar-raw
      valueFiles:
      - ../../values/clinvar-raw-stream/values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
