apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-secrets
  namespace: argocd
spec:
  project: prod
  source:
    repoURL: https://github.com/clingen-data-model/architecture.git
    targetRevision: HEAD
    path: services/prod/secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy: {}
