ingress:
  static_ip_name: "global-stage-clinvar-submitter-ip"
  clinvar_hostnames:
    - "clinvar-submitter.stage.clingen.app"
image:
  repository: gcr.io/clingen-stage/clinvar-submitter
  pullPolicy: Always
  tag: "3a9e898d4fea7e98095ac38e362894281facd592"
scv_service_url: "https://clinvarscv-wxzzxdssga-uc.a.run.app"
resources:
  requests:
    cpu: 500m
    memory: 350Mi
  limits:
    cpu: 1000m
    memory: 1Gi
