ingress:
  static_ip_name: "global-stage-clinvar-submitter-ip"
  clinvar_hostnames:
    - "clinvar-submitter.stage.clingen.app"
image:
  repository: gcr.io/clingen-stage/clinvar-submitter
  pullPolicy: Always
  tag: "acd6a7f5ab14a4a27acc4b4015476f3f75246926"
scv_service_url: "https://clinvarscv-wxzzxdssga-uc.a.run.app"
resources:
  requests:
    cpu: 500m
    memory: 350Mi
  limits:
    cpu: 1000m
    memory: 1Gi
