ingress:
  static_ip_name: "global-stage-clinvar-submitter-ip"
  clinvar_hostnames:
    - "clinvar-submitter.stage.clingen.app"
image:
  repository: gcr.io/clingen-stage/clinvar-submitter
  pullPolicy: Always
  tag: "bed0c674927ae1be05af5c90a6cef0c5f8e26387"
scv_service_url: "https://us-central1-clingen-dx.cloudfunctions.net/ClinVarSCV"
resources:
  requests:
    cpu: 500m
    memory: 350Mi
  limits:
    cpu: 1000m
    memory: 1Gi
