releases:
  - name: genegraph
    namespace: default
    chart: ../charts/clingen-genegraph
    values:
    - ../values/genegraph/values-prod.yaml
  - name: clingen-argocd
    namespace: argocd
    chart: ../charts/clingen-argocd

