# Tee see template values -
# cd architecture/helm
# helm template genegraph-gvdev charts/clingen-genegraph/ -f values/genegraph-gvdev/values-dev.yaml
genegraph_docker_image_name: gcr.io/clingen-dev/genegraph
genegraph_docker_image_tag: gvdev.51de602c0ee93ebfe5ec8ee2bcad704719c2396d
genegraph_image_version_envvar: true
genegraph_data_version: "2022-01-12T1430"
genegraph_cg_search_topics: "gene-validity-raw;gci-legacy-report-only"
genegraph_gcs_bucket: genegraph-dev
genegraph_gql_cache: false
genegraph_validate_events: false
genegraph_response_cache: true
genegraph_experimental_schema: true
# certificate and ingress
genegraph_mcrt_domains:
  - 'genegraph-gvdev.clingen.app'
genegraph_static_ip_name: global-dev-genegraph-gvdev-ip
genegraph_run_migration: true
genegraph_batch_event_sources: gci-raw-snapshot
