# Tee see template values -
# cd architecture/helm
# helm template genegraph-gvdev charts/clingen-genegraph/ -f values/genegraph-gvdev/values-dev.yaml
genegraph_docker_image_name: gcr.io/clingen-dev/genegraph
genegraph_docker_image_tag: gvdev.d6d6fef3e42c4e749d1a93f87e256d146f6fe881
genegraph_image_version_envvar: true
genegraph_data_version: "2022-06-08T1910"
genegraph_cg_search_topics: "gene-validity-raw;gci-legacy-report-only;actionability;gene-dosage-jira"
genegraph_gcs_bucket: genegraph-dev
genegraph_gql_cache: false
genegraph_validate_events: false
genegraph_response_cache: true
genegraph_experimental_schema: true
# certificate and ingress
genegraph_mcrt_domains:
  - 'genegraph-gvdev.clingen.app'
genegraph_static_ip_name: global-dev-genegraph-gvdev-ip
genegraph_run_migration: true
genegraph_batch_event_sources: "gci-raw-snapshot;gene-dosage-restored;gci-raw-missing-data;gci-express-json;gci-neo4j-report-only"
# genegraph_migration_data_version: "2022-02-22T1737:gvdev.6bcb9fd34e0ceb82ea17d20423b5af211d60f533"
